name: Daily Commit

on:
  schedule:
    # IST → UTC
    - cron: "30 18 * * *"  # 12:00 AM IST
    - cron: "30 0 * * *"   # 6:00 AM IST
    - cron: "30 6 * * *"   # 12:00 PM IST
    - cron: "30 12 * * *"  # 6:00 PM IST

  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Update file
        run: |
          echo "$(TZ='Asia/Kolkata' date)" >> daily-commit.txt

      - name: Commit and push changes
        run: |
          git config user.name "prajwalnikam"
          git config user.email "prajwalnikam2002@gmail.com"
          git add daily-commit.txt
          git commit -m "Daily update: $(TZ='Asia/Kolkata' date)" || exit 0
          git push
